# Generated by Django 5.2 on 2025-11-21 20:07

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='نام کاربری')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل')),
                ('password', models.CharField(max_length=255, verbose_name='رمز عبور هش\u200cشده')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='عکس پروفایل')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی کوتاه')),
                ('about', models.TextField(blank=True, null=True, verbose_name='درباره کاربر')),
                ('role', models.CharField(choices=[('customer', 'مشتری'), ('seller', 'فروشنده'), ('trainer', 'مربی'), ('admin', 'مدیر داخلی سیستم')], default='customer', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده؟')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت\u200cنام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییرات')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='آخرین فعالیت')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخرین آی\u200cپی ورود')),
                ('last_device', models.CharField(blank=True, max_length=120, null=True, verbose_name='آخرین دستگاه ورود')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-created_at'],
            },
        ),
    ]
