# Generated by Django 5.2 on 2025-12-01 16:17

import django.db.models.deletion
import utlis.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('avatar', models.ImageField(blank=True, upload_to='gateway/', verbose_name='avatar')),
                ('is_enable', models.BooleanField(default=True, verbose_name='is_enable')),
                ('credentials', models.TextField(blank=True, verbose_name='credentials')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
            ],
            options={
                'verbose_name': 'Gateway',
                'verbose_name_plural': 'Gateways',
                'db_table': 'gateway',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='price')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Void'), (10, 'Paid'), (20, 'Error'), (30, 'Canceled'), (31, 'Refunded')], db_index=True, default=0, verbose_name='status')),
                ('device_uuid', models.CharField(blank=True, max_length=40, verbose_name='device_uuid')),
                ('token', models.CharField(max_length=255)),
                ('phone_number', models.BigIntegerField(db_index=True, validators=[utlis.validators.PhoneNumberValidator()], verbose_name='phone_number')),
                ('consumed_code', models.PositiveIntegerField(db_index=True, null=True, verbose_name='consumed refrence code ')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created_time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='payment.gateway', verbose_name='gateway')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
            },
        ),
    ]
