# Generated by Django 5.2 on 2025-11-22 06:09

import django.db.models.deletion
import utlis.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='package')),
                ('sku', models.CharField(db_index=True, max_length=20, validators=[utlis.validators.SKUValidator()], verbose_name='suck keeping unit')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('avatar', models.ImageField(blank=True, upload_to='packages/', verbose_name='avatar')),
                ('is_enable', models.BooleanField(default=True, verbose_name='is_enable')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'packages',
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('expire_time', models.DateTimeField(auto_now=True, verbose_name='expire_time')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='subscriptions.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='users.appuser')),
            ],
            options={
                'verbose_name': 'Subscripion',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'subscriptions',
            },
        ),
    ]
